from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

GENERATED_FILES = (
    "AGENTS.md",
    "CLAUDE.md",
    ".claude/commands/shape-idea.md",
    ".cursor/rules/agent-work.mdc",
)

DISTRIBUTION_FILES = (
    ".opencode/commands/shape-idea.md",
    ".claude-plugin/marketplace.json",
    "plugins/portable-agent-workflows/.claude-plugin/plugin.json",
    "plugins/portable-agent-workflows/skills/shape-idea/SKILL.md",
)

MARKER = "<!-- GENERATED BY tools/generate_harness_integrations.py; DO NOT EDIT. -->"


def _read(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def test_generated_harness_files_exist_with_marker_and_agent_work_references() -> None:
    for relative_path in GENERATED_FILES:
        path = REPO_ROOT / relative_path
        assert path.exists(), f"missing generated file {relative_path}"
        text = _read(relative_path)
        assert MARKER in text
        assert ".agent-work/" in text
        assert "does not redefine the domain model" in text


def test_generated_harness_files_are_current() -> None:
    result = subprocess.run(
        [sys.executable, "tools/generate_harness_integrations.py", "--check"],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr


def test_distribution_files_exist_and_reference_agent_work() -> None:
    for relative_path in DISTRIBUTION_FILES:
        path = REPO_ROOT / relative_path
        assert path.exists(), f"missing distribution file {relative_path}"
        text = _read(relative_path)
        assert "portable-agent-workflows" in text

    opencode_command = _read(".opencode/commands/shape-idea.md")
    assert "description:" in opencode_command
    assert ".agent-work/" in opencode_command

    marketplace = _read(".claude-plugin/marketplace.json")
    assert '"plugins"' in marketplace
    assert '"source": "./plugins/portable-agent-workflows"' in marketplace

    plugin_skill = _read("plugins/portable-agent-workflows/skills/shape-idea/SKILL.md")
    assert "name: shape-idea" in plugin_skill
    assert "agent-work-v1" in plugin_skill
