from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

GENERATED_FILES = (
    "AGENTS.md",
    "CLAUDE.md",
    ".claude/commands/shape-idea.md",
    ".cursor/rules/agent-work.mdc",
)

MARKER = "<!-- GENERATED BY tools/generate_harness_integrations.py; DO NOT EDIT. -->"


def _read(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def test_generated_harness_files_exist_with_marker_and_agent_work_references() -> None:
    for relative_path in GENERATED_FILES:
        path = REPO_ROOT / relative_path
        assert path.exists(), f"missing generated file {relative_path}"
        text = _read(relative_path)
        assert MARKER in text
        assert ".agent-work/" in text
        assert "does not redefine the domain model" in text


def test_generated_harness_files_are_current() -> None:
    result = subprocess.run(
        [sys.executable, "tools/generate_harness_integrations.py", "--check"],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr
