from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_ROOT = REPO_ROOT / "tools" / "harness_templates"
MARKER = "<!-- GENERATED BY tools/generate_harness_integrations.py; DO NOT EDIT. -->"


@dataclass(frozen=True)
class GeneratedFile:
    template: str
    output: str


GENERATED_FILES = (
    GeneratedFile("agents.md.tmpl", "AGENTS.md"),
    GeneratedFile("claude.md.tmpl", "CLAUDE.md"),
    GeneratedFile("claude-shape-idea.md.tmpl", ".claude/commands/shape-idea.md"),
    GeneratedFile("cursor-agent-work.mdc.tmpl", ".cursor/rules/agent-work.mdc"),
)

REQUIRED_SOURCES = (
    ".agent-work/glossary.md",
    ".agent-work/skills/shape-idea/SKILL.md",
    ".agent-work/skills/shape-spec/SKILL.md",
    ".agent-work/skills/create-phased-plan/SKILL.md",
    ".agent-work/adapters/codex.md",
    ".agent-work/adapters/claude.md",
    ".agent-work/adapters/cursor.md",
)


def _read(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"missing required file: {path.relative_to(REPO_ROOT)}")
    return path.read_text(encoding="utf-8")


def _render(template_name: str) -> str:
    template = _read(TEMPLATE_ROOT / template_name)
    rendered = template.format(
        marker=MARKER,
        glossary=".agent-work/glossary.md",
        shape_idea=".agent-work/skills/shape-idea/SKILL.md",
        shape_spec=".agent-work/skills/shape-spec/SKILL.md",
        create_phased_plan=".agent-work/skills/create-phased-plan/SKILL.md",
        codex_adapter=".agent-work/adapters/codex.md",
        claude_adapter=".agent-work/adapters/claude.md",
        cursor_adapter=".agent-work/adapters/cursor.md",
    )
    if not rendered.endswith("\n"):
        rendered += "\n"
    return rendered


def render_all() -> dict[Path, str]:
    for source in REQUIRED_SOURCES:
        _read(REPO_ROOT / source)
    return {
        REPO_ROOT / generated.output: _render(generated.template) for generated in GENERATED_FILES
    }


def write_all(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_all(rendered: dict[Path, str]) -> list[Path]:
    stale: list[Path] = []
    for path, expected in rendered.items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate native harness integration files.")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale.")
    args = parser.parse_args()

    try:
        rendered = render_all()
        if args.check:
            stale = check_all(rendered)
            if stale:
                print("Stale generated harness files:")
                for path in stale:
                    print(f"- {path.relative_to(REPO_ROOT)}")
                return 1
            print("Generated harness files are current.")
            return 0

        write_all(rendered)
        print("Generated harness integration files.")
        return 0
    except FileNotFoundError as error:
        print(str(error), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
